"""TestGenerator, the Phase 1 test-generation engine (Task 1.12b).

Takes a source file, detects its language and framework, builds a
short prompt, calls ``claude -p`` via subprocess, parses the response,
writes the generated test file with a mandatory review header, and
runs a per-language compile check. On compile failure, deletes the
file and raises ``GenerationError`` with the compile output so the
caller can surface a helpful error.

Design rules (all enforced in code, tested in ``tests/test_generator.py``):

- NEVER commits. The generator never invokes git in any form.
- NEVER overwrites existing tests. If the target path already exists,
  the generator raises ``GeneratorSkipped`` and leaves both the source
  and the existing test untouched.
- NEVER returns a broken file. A failing compile check always deletes
  the file before raising.
- NEVER hard-codes a venv or toolchain. All subprocess calls go
  through the claude CLI or an on-PATH binary.

Per ADR 0009, test generation makes tailtest useful for projects with
zero tests. The generator is invoked from the ``generate_tests`` MCP
tool and from the ``/tailtest:gen`` skill.
"""

from __future__ import annotations

import asyncio
import json
import logging
import shutil
from dataclasses import dataclass
from pathlib import Path

from tailtest.core.generator.compile_check import CompileCheckResult, check_file
from tailtest.core.generator.prompts import SYSTEM_PROMPT, build_user_prompt

logger = logging.getLogger(__name__)


_PYTHON_HEADER = "# generated by tailtest, review before committing"
_JS_HEADER = "// generated by tailtest, review before committing"

_SUPPORTED_LANGUAGES = ("python", "typescript", "javascript")
_DEFAULT_FRAMEWORKS = {
    "python": "pytest",
    "typescript": "vitest",
    "javascript": "vitest",
}

# Map source extensions to language names.
_LANG_BY_SUFFIX = {
    ".py": "python",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
}


class GenerationError(RuntimeError):
    """Raised when test generation fails in a way the user should see.

    Covers: claude CLI missing, claude CLI timeout, unparseable
    response, compile check failure (after the broken file has been
    deleted), filesystem write errors.
    """


class GeneratorSkipped(RuntimeError):
    """Raised when generation is deliberately skipped.

    Examples: the target test file already exists, the source file
    is itself a test file, the source file is in an unsupported
    language. Distinct from ``GenerationError`` because callers
    typically want to treat a skip as informational, not a failure.
    """


@dataclass(frozen=True)
class GeneratedTest:
    """Result of a successful generation."""

    source_path: Path
    test_path: Path
    language: str
    framework: str
    preview: str
    compile_check: CompileCheckResult


class TestGenerator:
    """Builds starter tests for source files via ``claude -p``.

    Construction takes the project root and an optional framework
    override. The default framework per language is chosen by
    ``_DEFAULT_FRAMEWORKS``; override via ``framework_override`` to
    force ``jest`` instead of ``vitest`` for TS/JS, for example.
    """

    # Tell pytest this is NOT a test class, despite starting with "Test".
    # The name is chosen for the public API ("a generator of tests");
    # pytest's default discovery rule would otherwise try to collect
    # this class as a test case and emit a PytestCollectionWarning.
    __test__ = False

    def __init__(
        self,
        project_root: Path,
        *,
        framework_override: str | None = None,
        claude_bin: str = "claude",
        subprocess_timeout_seconds: float = 120.0,
    ) -> None:
        self.project_root = Path(project_root).resolve()
        self.framework_override = framework_override
        self.claude_bin = claude_bin
        self.subprocess_timeout_seconds = subprocess_timeout_seconds

    # --- Public API ---

    async def generate(
        self,
        source: Path,
        *,
        scope: str = "module",
    ) -> GeneratedTest:
        """Generate a starter test for ``source`` and return the result.

        Raises ``GeneratorSkipped`` when generation is not applicable
        (unsupported language, already a test file, target already
        exists). Raises ``GenerationError`` when generation fails for
        any actionable reason.
        """
        source = Path(source).resolve()
        if not source.exists():
            raise GeneratorSkipped(f"source file does not exist: {source}")
        if not source.is_file():
            raise GeneratorSkipped(f"source path is not a file: {source}")

        language = self._detect_language(source)
        if language not in _SUPPORTED_LANGUAGES:
            raise GeneratorSkipped(f"unsupported language for source: {source.suffix}")

        if self._looks_like_test_file(source):
            raise GeneratorSkipped(f"source file is itself a test file: {source}")

        framework = self.framework_override or _DEFAULT_FRAMEWORKS[language]
        header = _PYTHON_HEADER if language == "python" else _JS_HEADER

        test_path = self._resolve_test_path(source, language)
        if test_path.exists():
            raise GeneratorSkipped(
                f"target test file already exists: {test_path}, refusing to overwrite"
            )

        source_text = source.read_text(encoding="utf-8")

        # Build the prompt.
        user_prompt = build_user_prompt(
            source_path=str(source.relative_to(self.project_root))
            if self._is_under_root(source)
            else str(source),
            source_text=source_text,
            language=language,
            framework=framework,
            header_line=header,
            scope=scope,
        )

        generated_text = await self._call_claude(user_prompt)
        generated_text = self._strip_fences(generated_text)

        if not generated_text.strip():
            raise GenerationError("claude returned empty output")
        if header not in generated_text.splitlines()[0] if generated_text.splitlines() else True:
            # The model did not honor the mandatory header. Prepend it
            # ourselves rather than fail, so the user still gets a
            # usable file. Log the anomaly for later review.
            logger.warning("generator response missing header line, prepending")
            generated_text = f"{header}\n{generated_text.lstrip()}"

        # Ensure the assertion guarantee. If the generated file has no
        # assertion keyword, fail loudly so the user does not ship
        # vacuous scaffolding.
        if not self._has_assertion(generated_text, language):
            raise GenerationError(
                "claude output does not contain any assertion. Regenerate or author by hand."
            )

        test_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            test_path.write_text(generated_text, encoding="utf-8")
        except OSError as exc:
            raise GenerationError(f"could not write test file {test_path}: {exc}") from exc

        check = await check_file(test_path, language)
        if not check.ok:
            # Delete the broken file before surfacing the error. The
            # caller must never see a half-written test on disk.
            try:
                test_path.unlink()
            except OSError:
                logger.warning("could not delete broken generated file: %s", test_path)
            raise GenerationError(
                f"compile check failed for {test_path} ({check.tool}): {check.message}"
            )

        return GeneratedTest(
            source_path=source,
            test_path=test_path,
            language=language,
            framework=framework,
            preview=self._make_preview(generated_text),
            compile_check=check,
        )

    # --- Internal helpers ---

    def _detect_language(self, source: Path) -> str:
        return _LANG_BY_SUFFIX.get(source.suffix.lower(), "")

    def _looks_like_test_file(self, source: Path) -> bool:
        name = source.name.lower()
        if name.startswith("test_") and name.endswith(".py"):
            return True
        if any(part in {"tests", "test", "__tests__"} for part in source.parts):
            # Only treat as a test file if it also matches a test naming
            # pattern. A source file inside a tests/ directory that is
            # not itself a test (e.g. a helper) should still be generatable.
            if name.endswith((".test.ts", ".test.tsx", ".test.js", ".test.jsx")):
                return True
            if name.endswith((".spec.ts", ".spec.tsx", ".spec.js", ".spec.jsx")):
                return True
            if name.startswith("test_") and name.endswith(".py"):
                return True
        return False

    def _resolve_test_path(self, source: Path, language: str) -> Path:
        """Decide where the generated test file should land.

        Python:  tests/unit/test_<stem>.py (relative to project root)
        TS/JS:   tests/<stem>.test.<ext> (relative to project root)
        """
        if language == "python":
            return self.project_root / "tests" / "unit" / f"test_{source.stem}.py"
        # TS and JS share the same shape; keep the original extension.
        ext = source.suffix.lower()
        if ext in (".mts", ".cts"):
            ext = ".ts"
        if ext in (".mjs", ".cjs"):
            ext = ".js"
        return self.project_root / "tests" / f"{source.stem}.test{ext}"

    def _is_under_root(self, path: Path) -> bool:
        try:
            path.relative_to(self.project_root)
            return True
        except ValueError:
            return False

    async def _call_claude(self, user_prompt: str) -> str:
        """Invoke ``claude -p`` and return the inner result text.

        Mirrors the transport in ``tailtest.llm.claude_cli``: uses
        ``--output-format json`` and extracts the ``result`` field
        from the outer envelope. Strips markdown fences in a follow-up
        pass (see ``_strip_fences``).
        """
        if shutil.which(self.claude_bin) is None:
            raise GenerationError(
                "claude CLI not found on PATH. Install claude or set TAILTEST_GENERATOR_CLAUDE_BIN."
            )

        try:
            proc = await asyncio.create_subprocess_exec(
                self.claude_bin,
                "-p",
                user_prompt,
                "--output-format",
                "json",
                "--append-system-prompt",
                SYSTEM_PROMPT,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=self.subprocess_timeout_seconds
            )
        except FileNotFoundError as exc:
            raise GenerationError(f"claude CLI not found: {exc}") from exc
        except TimeoutError as exc:
            raise GenerationError(
                f"claude subprocess timed out after {self.subprocess_timeout_seconds}s"
            ) from exc

        stdout_text = stdout_bytes.decode(errors="replace")
        stderr_text = stderr_bytes.decode(errors="replace")

        if (proc.returncode or 0) != 0:
            detail = stderr_text.strip() or f"exit code {proc.returncode}"
            raise GenerationError(f"claude CLI exited with error: {detail}")

        try:
            outer = json.loads(stdout_text)
        except json.JSONDecodeError as exc:
            raise GenerationError(
                f"claude CLI returned non-JSON output (first 200 chars): {stdout_text[:200]}"
            ) from exc

        result = outer.get("result")
        if not isinstance(result, str) or not result.strip():
            raise GenerationError(
                f"claude CLI response missing 'result' field: {stdout_text[:200]}"
            )
        return result

    @staticmethod
    def _strip_fences(text: str) -> str:
        """Remove triple-backtick fences the model may have added around the body."""
        stripped = text.strip()
        if stripped.startswith("```"):
            # Drop the first line (the opening fence, possibly with a
            # language tag).
            stripped = stripped.split("\n", 1)[-1]
        if stripped.endswith("```"):
            stripped = stripped.rsplit("```", 1)[0]
        return stripped.strip() + "\n"

    @staticmethod
    def _has_assertion(text: str, language: str) -> bool:
        """Return True if the generated text contains at least one assertion.

        Python: ``assert`` keyword or ``pytest.raises``.
        TS/JS: ``expect(...)`` or ``assert(...)`` from node:assert.
        """
        lowered = text
        if language == "python":
            return "assert " in lowered or "pytest.raises" in lowered
        return "expect(" in lowered or "assert(" in lowered or "assert.equal" in lowered

    @staticmethod
    def _make_preview(text: str, *, max_lines: int = 20) -> str:
        lines = text.splitlines()
        if len(lines) <= max_lines:
            return "\n".join(lines)
        return "\n".join(lines[:max_lines]) + f"\n... ({len(lines) - max_lines} more lines)"
