# Copyright 2026 AvanSaber Inc.
# SPDX-License-Identifier: Apache-2.0

"""TestGenerator, the Phase 1 test-generation engine (Task 1.12b).

Takes a source file, detects its language and framework, builds a
short prompt, calls ``claude -p`` via subprocess, parses the response,
writes the generated test file with a mandatory review header, and
runs a per-language compile check. On compile failure, deletes the
file and raises ``GenerationError`` with the compile output so the
caller can surface a helpful error.

Design rules (all enforced in code, tested in ``tests/test_generator.py``):

- NEVER commits. The generator never invokes git in any form.
- NEVER overwrites existing tests. If the target path already exists,
  the generator raises ``GeneratorSkipped`` and leaves both the source
  and the existing test untouched.
- NEVER returns a broken file. A failing compile check always deletes
  the file before raising.
- NEVER hard-codes a venv or toolchain. All subprocess calls go
  through the claude CLI or an on-PATH binary.

Per ADR 0009, test generation makes tailtest useful for projects with
zero tests. The generator is invoked from the ``generate_tests`` MCP
tool and from the ``/tailtest:gen`` skill.
"""

from __future__ import annotations

import asyncio
import json
import logging
import shutil
import tomllib
from dataclasses import dataclass
from pathlib import Path

from tailtest.core.generator.ast_signals import (
    build_category_hints,
    build_detection_note,
    cluster_domain_from_source_tree,
    extract_domain_signals,
)
from tailtest.core.generator.compile_check import CompileCheckResult, check_file
from tailtest.core.generator.prompts import (
    RUST_SYSTEM_PROMPT,
    SYSTEM_PROMPT,
    ProjectContext,
    build_rust_user_prompt,
    build_user_prompt,
)

logger = logging.getLogger(__name__)


_PYTHON_HEADER = "# generated by tailtest, review before committing"
_JS_HEADER = "// generated by tailtest, review before committing"
_RS_HEADER = "// generated by tailtest - review before committing"

_SUPPORTED_LANGUAGES = ("python", "typescript", "javascript", "rust")

# Extensions to search for when sampling existing test style, by language.
_TEST_STYLE_EXTS: dict[str, frozenset[str]] = {
    "python": frozenset({".py"}),
    "typescript": frozenset({".ts", ".tsx"}),
    "javascript": frozenset({".js", ".jsx"}),
}

_SAMPLE_LINES = 30
_SAMPLE_MAX_CHARS = 1_200
_TRUNCATE_MARKER = "# ... (truncated)"
_PROMPT_BUDGET = 7_500
_DEFAULT_FRAMEWORKS = {
    "python": "pytest",
    "typescript": "vitest",
    "javascript": "vitest",
    "rust": "cargo",
}

# Map source extensions to language names.
_LANG_BY_SUFFIX = {
    ".py": "python",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".rs": "rust",
}


class GenerationError(RuntimeError):
    """Raised when test generation fails in a way the user should see.

    Covers: claude CLI missing, claude CLI timeout, unparseable
    response, compile check failure (after the broken file has been
    deleted), filesystem write errors.
    """


class GeneratorSkipped(RuntimeError):
    """Raised when generation is deliberately skipped.

    Examples: the target test file already exists, the source file
    is itself a test file, the source file is in an unsupported
    language. Distinct from ``GenerationError`` because callers
    typically want to treat a skip as informational, not a failure.
    """


@dataclass(frozen=True)
class GeneratedTest:
    """Result of a successful generation."""

    source_path: Path
    test_path: Path
    language: str
    framework: str
    preview: str
    compile_check: CompileCheckResult


class TestGenerator:
    """Builds starter tests for source files via ``claude -p``.

    Construction takes the project root and an optional framework
    override. The default framework per language is chosen by
    ``_DEFAULT_FRAMEWORKS``; override via ``framework_override`` to
    force ``jest`` instead of ``vitest`` for TS/JS, for example.
    """

    # Tell pytest this is NOT a test class, despite starting with "Test".
    # The name is chosen for the public API ("a generator of tests");
    # pytest's default discovery rule would otherwise try to collect
    # this class as a test case and emit a PytestCollectionWarning.
    __test__ = False

    def __init__(
        self,
        project_root: Path,
        *,
        framework_override: str | None = None,
        claude_bin: str = "claude",
        subprocess_timeout_seconds: float = 120.0,
    ) -> None:
        self.project_root = Path(project_root).resolve()
        self.framework_override = framework_override
        self.claude_bin = claude_bin
        self.subprocess_timeout_seconds = subprocess_timeout_seconds

    # --- Public API ---

    async def generate(
        self,
        source: Path,
        *,
        scope: str = "module",
        user_context: str | None = None,
    ) -> GeneratedTest:
        """Generate a starter test for ``source`` and return the result.

        Raises ``GeneratorSkipped`` when generation is not applicable
        (unsupported language, already a test file, target already
        exists). Raises ``GenerationError`` when generation fails for
        any actionable reason.
        """
        source = Path(source).resolve()
        if not source.exists():
            raise GeneratorSkipped(f"source file does not exist: {source}")
        if not source.is_file():
            raise GeneratorSkipped(f"source path is not a file: {source}")

        language = self._detect_language(source)
        if language not in _SUPPORTED_LANGUAGES:
            raise GeneratorSkipped(f"unsupported language for source: {source.suffix}")

        # Rust has fundamentally different test layout semantics (colocated
        # tests vs integration tests, append-to-source vs new file).
        # Dispatch to the dedicated implementation before the generic path.
        if language == "rust":
            return await self._generate_rust(source, scope)

        if self._looks_like_test_file(source):
            raise GeneratorSkipped(f"source file is itself a test file: {source}")

        framework = self.framework_override or _DEFAULT_FRAMEWORKS[language]
        header = _PYTHON_HEADER if language == "python" else _JS_HEADER

        test_path = self._resolve_test_path(source, language)
        if test_path.exists():
            raise GeneratorSkipped(
                f"target test file already exists: {test_path}, refusing to overwrite"
            )

        source_text = source.read_text(encoding="utf-8")

        # Build the prompt.
        project_context = self._load_project_context()
        signals = extract_domain_signals(source)
        hints = build_category_hints(
            signals,
            likely_vibe_coded=project_context.likely_vibe_coded if project_context else False,
        )
        tests_dirs = list(project_context.tests_dirs) if project_context else []
        test_style = self._sample_test_style(source, language, tests_dirs)

        # Vibe-coded path: cluster sibling function names when no existing
        # tests are available to sample from.
        domain_cluster: str | None = None
        vibe_coded = project_context.likely_vibe_coded if project_context else False
        if vibe_coded and test_style is None:
            domain_cluster = cluster_domain_from_source_tree(source, self.project_root)

        source_label = str(source.relative_to(self.project_root)) if self._is_under_root(source) else str(source)

        # Budget guard: build with all optional sections, then strip in
        # priority order until under the character threshold.
        effective_style = test_style
        effective_signals = signals
        effective_hints: list[str] | None = hints or None
        _prompt_kwargs: dict = dict(
            source_path=source_label,
            source_text=source_text,
            language=language,
            framework=framework,
            header_line=header,
            scope=scope,
            project_context=project_context,
            domain_signals=effective_signals,
            category_hints=effective_hints,
            test_style_sample=effective_style,
            domain_cluster=domain_cluster,
        )
        trial = build_user_prompt(**_prompt_kwargs)
        if len(trial) > _PROMPT_BUDGET:
            effective_style = None
            _prompt_kwargs["test_style_sample"] = None
            trial = build_user_prompt(**_prompt_kwargs)
        if len(trial) > _PROMPT_BUDGET:
            effective_signals = None
            _prompt_kwargs["domain_signals"] = None
            _prompt_kwargs["domain_cluster"] = None
            trial = build_user_prompt(**_prompt_kwargs)
        if len(trial) > _PROMPT_BUDGET:
            effective_hints = None
            _prompt_kwargs["category_hints"] = None
            trial = build_user_prompt(**_prompt_kwargs)
        if len(trial) > _PROMPT_BUDGET:
            logger.warning(
                "prompt budget exceeded on %s: %d chars. Context stripped, generating with source only.",
                source_label,
                len(trial),
            )
        user_prompt = trial

        generated_text = await self._call_claude(user_prompt)
        generated_text = self._strip_fences(generated_text)

        if not generated_text.strip():
            raise GenerationError("claude returned empty output")
        if header not in generated_text.splitlines()[0] if generated_text.splitlines() else True:
            # The model did not honor the mandatory header. Prepend it
            # ourselves rather than fail, so the user still gets a
            # usable file. Log the anomaly for later review.
            logger.warning("generator response missing header line, prepending")
            generated_text = f"{header}\n{generated_text.lstrip()}"

        # Ensure the assertion guarantee. If the generated file has no
        # assertion keyword, fail loudly so the user does not ship
        # vacuous scaffolding.
        if not self._has_assertion(generated_text, language):
            raise GenerationError(
                "claude output does not contain any assertion. Regenerate or author by hand."
            )

        # Insert detection note as line 2 (after mandatory header).
        note = build_detection_note(signals, project_context, user_context, language=language)
        generated_text = self._insert_detection_note(generated_text, note)

        test_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            test_path.write_text(generated_text, encoding="utf-8")
        except OSError as exc:
            raise GenerationError(f"could not write test file {test_path}: {exc}") from exc

        check = await check_file(test_path, language)
        if not check.ok:
            # Delete the broken file before surfacing the error. The
            # caller must never see a half-written test on disk.
            try:
                test_path.unlink()
            except OSError:
                logger.warning("could not delete broken generated file: %s", test_path)
            raise GenerationError(
                f"compile check failed for {test_path} ({check.tool}): {check.message}"
            )

        return GeneratedTest(
            source_path=source,
            test_path=test_path,
            language=language,
            framework=framework,
            preview=self._make_preview(generated_text),
            compile_check=check,
        )

    # --- Rust-specific generation -----------------------------------------

    async def _generate_rust(self, source: Path, scope: str) -> GeneratedTest:
        """Generate Rust tests for a source file.

        Handles two styles:
        - ``colocated``: Appends a ``#[cfg(test)] mod tests { ... }`` block
          to the source file itself. This is the most idiomatic Rust unit
          test pattern.
        - ``integration``: Creates a new file in ``tests/<name>_test.rs``
          at the crate root. Used when the project already has integration
          tests in a ``tests/`` directory.

        Style is detected from existing test patterns in the crate. When in
        doubt, ``colocated`` is preferred.
        """
        if self._looks_like_rust_integration_test(source):
            raise GeneratorSkipped(f"source file is a Rust integration test: {source}")

        source_text = source.read_text(encoding="utf-8")
        style = self._detect_rust_test_style(source)

        if style == "colocated":
            if "#[cfg(test)]" in source_text:
                raise GeneratorSkipped(f"source file already has a #[cfg(test)] block: {source}")
            test_path = source  # We append to the source file itself.
        else:
            test_path = self._resolve_rust_integration_test_path(source)
            if test_path.exists():
                raise GeneratorSkipped(
                    f"integration test file already exists: {test_path}, refusing to overwrite"
                )

        crate_name = self._rust_crate_name(source) or source.parent.name

        user_prompt = build_rust_user_prompt(
            source_path=str(source.relative_to(self.project_root))
            if self._is_under_root(source)
            else str(source),
            source_text=source_text,
            style=style,
            crate_name=crate_name,
            scope=scope,
        )

        generated_text = await self._call_claude(user_prompt, system_prompt=RUST_SYSTEM_PROMPT)
        generated_text = self._strip_fences(generated_text)

        if not generated_text.strip():
            raise GenerationError("claude returned empty output")

        lines = generated_text.splitlines()
        if not lines or _RS_HEADER not in lines[0]:
            logger.warning("generator response missing Rust header line, prepending")
            generated_text = f"{_RS_HEADER}\n{generated_text.lstrip()}"

        if not self._has_assertion(generated_text, "rust"):
            raise GenerationError(
                "claude output does not contain any assertion. Regenerate or author by hand."
            )

        # Insert detection note as line 2.
        rust_signals = extract_domain_signals(source)
        rust_note = build_detection_note(
            rust_signals, self._load_project_context(), None, language="rust"
        )
        generated_text = self._insert_detection_note(generated_text, rust_note)

        # Write the output.  For colocated tests, append to the source file;
        # for integration tests, create a new file.
        if style == "colocated":
            new_content = source_text.rstrip() + "\n\n" + generated_text.rstrip() + "\n"
            try:
                source.write_text(new_content, encoding="utf-8")
            except OSError as exc:
                raise GenerationError(f"could not write to {source}: {exc}") from exc
        else:
            test_path.parent.mkdir(parents=True, exist_ok=True)
            try:
                test_path.write_text(generated_text, encoding="utf-8")
            except OSError as exc:
                raise GenerationError(f"could not write test file {test_path}: {exc}") from exc

        check = await check_file(test_path, "rust")
        if not check.ok:
            # Rollback: restore the original source for colocated; delete
            # the new file for integration.
            if style == "colocated":
                try:
                    source.write_text(source_text, encoding="utf-8")
                except OSError:
                    logger.warning("could not restore %s after compile failure", source)
            else:
                try:
                    test_path.unlink()
                except OSError:
                    logger.warning("could not delete broken generated file: %s", test_path)
            raise GenerationError(
                f"compile check failed for {test_path} ({check.tool}): {check.message}"
            )

        return GeneratedTest(
            source_path=source,
            test_path=test_path,
            language="rust",
            framework="cargo",
            preview=self._make_preview(generated_text),
            compile_check=check,
        )

    # --- Internal helpers ---

    def _load_project_context(self) -> ProjectContext | None:
        """Load project profile and return a ``ProjectContext``, or ``None``.

        Reuses ``ProjectScanner.load_profile()`` from the scan subsystem --
        never re-implements profile.json loading. Returns ``None`` on any
        failure (missing profile, malformed JSON, import error) and logs at
        DEBUG so the caller always gets a usable fallback.
        """
        try:
            from tailtest.core.scan.scanner import ProjectScanner  # noqa: PLC0415

            scanner = ProjectScanner(self.project_root)
            profile = scanner.load_profile()
            if profile is None:
                return None
            runner = profile.runners_detected[0].name if profile.runners_detected else None
            framework_category = (
                profile.frameworks_detected[0].category
                if profile.frameworks_detected
                else ""
            )
            return ProjectContext(
                llm_summary=profile.llm_summary,
                primary_language=profile.primary_language,
                runner=runner,
                framework_category=framework_category,
                likely_vibe_coded=profile.likely_vibe_coded,
                tests_dirs=list(profile.directories.tests),
            )
        except Exception:  # noqa: BLE001
            logger.debug("failed to load project context for generator", exc_info=True)
            return None

    def _sample_test_style(
        self,
        source: Path,
        language: str,
        tests_dirs: list[Path],
    ) -> str | None:
        """Return the first N lines of the nearest existing test file.

        Step 1: check if the sibling test (computed via the same path
        heuristic as ``_resolve_test_path()``) already exists on disk.
        Step 2: if not, pick the most-recently-modified test file in
        ``tests_dirs`` (excluding conftest.py).
        Returns ``None`` when no existing test is found or ``tests_dirs``
        is empty -- the vibe-coded / zero-test case.
        Caps output at ``_SAMPLE_MAX_CHARS`` chars and appends a truncation
        marker if the sample is cut short.
        """
        sibling = self._resolve_test_path(source, language)

        candidate: Path | None = None
        if sibling.exists() and sibling != source:
            candidate = sibling

        if candidate is None:
            if not tests_dirs:
                return None
            exts = _TEST_STYLE_EXTS.get(language, frozenset({".py"}))
            best: Path | None = None
            best_mtime = -1.0
            for tests_dir in tests_dirs:
                if not tests_dir.is_dir():
                    continue
                for p in tests_dir.rglob("*"):
                    if not p.is_file() or p.suffix not in exts:
                        continue
                    if p.name == "conftest.py" or p == sibling:
                        continue
                    try:
                        mtime = p.stat().st_mtime
                    except OSError:
                        continue
                    if mtime > best_mtime:
                        best_mtime = mtime
                        best = p
            candidate = best

        if candidate is None:
            return None

        try:
            lines = candidate.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            return None

        sample = "\n".join(lines[:_SAMPLE_LINES])
        if len(sample) > _SAMPLE_MAX_CHARS:
            sample = sample[:_SAMPLE_MAX_CHARS] + "\n" + _TRUNCATE_MARKER
        return sample

    def _detect_language(self, source: Path) -> str:
        return _LANG_BY_SUFFIX.get(source.suffix.lower(), "")

    # --- Rust helpers ---

    def _find_rust_crate_root(self, path: Path) -> Path | None:
        """Walk up from ``path`` to find the directory containing ``Cargo.toml``."""
        current = path.parent if path.is_file() else path
        while True:
            if (current / "Cargo.toml").exists():
                return current
            parent = current.parent
            if parent == current:
                return None
            current = parent

    def _rust_crate_name(self, source: Path) -> str | None:
        """Return the ``[package].name`` from the nearest ``Cargo.toml``."""
        crate_root = self._find_rust_crate_root(source)
        if crate_root is None:
            return None
        try:
            data = tomllib.loads((crate_root / "Cargo.toml").read_text(encoding="utf-8"))
            pkg = data.get("package")
            if isinstance(pkg, dict):
                name = pkg.get("name")
                if isinstance(name, str):
                    return name
        except (OSError, tomllib.TOMLDecodeError):
            pass
        return None

    def _looks_like_rust_integration_test(self, source: Path) -> bool:
        """Return True if ``source`` is a Rust integration test file.

        Integration test files are ``.rs`` files placed directly inside a
        ``tests/`` directory that lives next to a ``Cargo.toml``.
        """
        if source.suffix.lower() != ".rs":
            return False
        parent = source.parent
        return parent.name == "tests" and (parent.parent / "Cargo.toml").exists()

    def _detect_rust_test_style(self, source: Path) -> str:
        """Return ``"colocated"`` or ``"integration"`` based on existing patterns.

        Scans up to 10 ``.rs`` files in ``src/`` for ``#[cfg(test)]``
        (colocated style). Falls back to checking for ``tests/*.rs`` files
        (integration style). Defaults to ``"colocated"`` when no pattern
        is found -- colocated is the more idiomatic Rust unit-test layout.
        """
        crate_root = self._find_rust_crate_root(source)
        if crate_root is None:
            return "colocated"

        # Prefer colocated if any src/ file already has #[cfg(test)].
        src_dir = crate_root / "src"
        if src_dir.is_dir():
            for rs_file in list(src_dir.rglob("*.rs"))[:10]:
                try:
                    content = rs_file.read_text(encoding="utf-8", errors="replace")
                    if "#[cfg(test)]" in content:
                        return "colocated"
                except OSError:
                    continue

        # Fall back to integration style if tests/*.rs files exist.
        tests_dir = crate_root / "tests"
        if tests_dir.is_dir() and any(tests_dir.glob("*.rs")):
            return "integration"

        return "colocated"

    def _resolve_rust_integration_test_path(self, source: Path) -> Path:
        """Compute the integration test file path for a Rust source file."""
        crate_root = self._find_rust_crate_root(source)
        if crate_root is None:
            crate_root = self.project_root
        return crate_root / "tests" / f"{source.stem}_test.rs"

    def _looks_like_test_file(self, source: Path) -> bool:
        name = source.name.lower()
        if name.startswith("test_") and name.endswith(".py"):
            return True
        if any(part in {"tests", "test", "__tests__"} for part in source.parts):
            # Only treat as a test file if it also matches a test naming
            # pattern. A source file inside a tests/ directory that is
            # not itself a test (e.g. a helper) should still be generatable.
            if name.endswith((".test.ts", ".test.tsx", ".test.js", ".test.jsx")):
                return True
            if name.endswith((".spec.ts", ".spec.tsx", ".spec.js", ".spec.jsx")):
                return True
            if name.startswith("test_") and name.endswith(".py"):
                return True
        return False

    def _resolve_test_path(self, source: Path, language: str) -> Path:
        """Decide where the generated test file should land.

        Python:  tests/unit/test_<stem>.py (relative to project root)
        TS/JS:   tests/<stem>.test.<ext> (relative to project root)
        """
        if language == "python":
            return self.project_root / "tests" / "unit" / f"test_{source.stem}.py"
        # TS and JS share the same shape; keep the original extension.
        ext = source.suffix.lower()
        if ext in (".mts", ".cts"):
            ext = ".ts"
        if ext in (".mjs", ".cjs"):
            ext = ".js"
        return self.project_root / "tests" / f"{source.stem}.test{ext}"

    def _is_under_root(self, path: Path) -> bool:
        try:
            path.relative_to(self.project_root)
            return True
        except ValueError:
            return False

    async def _call_claude(self, user_prompt: str, *, system_prompt: str | None = None) -> str:
        """Invoke ``claude -p`` and return the inner result text.

        Mirrors the transport in ``tailtest.llm.claude_cli``: uses
        ``--output-format json`` and extracts the ``result`` field
        from the outer envelope. Strips markdown fences in a follow-up
        pass (see ``_strip_fences``).

        ``system_prompt`` overrides the default ``SYSTEM_PROMPT``. Used
        for Rust generation which needs a different set of rules.
        """
        if shutil.which(self.claude_bin) is None:
            raise GenerationError(
                "claude CLI not found on PATH. Install claude or set TAILTEST_GENERATOR_CLAUDE_BIN."
            )

        effective_system_prompt = system_prompt if system_prompt is not None else SYSTEM_PROMPT

        try:
            proc = await asyncio.create_subprocess_exec(
                self.claude_bin,
                "-p",
                user_prompt,
                "--output-format",
                "json",
                "--append-system-prompt",
                effective_system_prompt,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=self.subprocess_timeout_seconds
            )
        except FileNotFoundError as exc:
            raise GenerationError(f"claude CLI not found: {exc}") from exc
        except TimeoutError as exc:
            raise GenerationError(
                f"claude subprocess timed out after {self.subprocess_timeout_seconds}s"
            ) from exc

        stdout_text = stdout_bytes.decode(errors="replace")
        stderr_text = stderr_bytes.decode(errors="replace")

        if (proc.returncode or 0) != 0:
            detail = stderr_text.strip() or f"exit code {proc.returncode}"
            raise GenerationError(f"claude CLI exited with error: {detail}")

        try:
            outer = json.loads(stdout_text)
        except json.JSONDecodeError as exc:
            raise GenerationError(
                f"claude CLI returned non-JSON output (first 200 chars): {stdout_text[:200]}"
            ) from exc

        result = outer.get("result")
        if not isinstance(result, str) or not result.strip():
            raise GenerationError(
                f"claude CLI response missing 'result' field: {stdout_text[:200]}"
            )
        return result

    @staticmethod
    def _insert_detection_note(text: str, note: str) -> str:
        """Insert ``note`` as the second line of ``text`` (after the header)."""
        lines = text.splitlines(keepends=True)
        if lines:
            lines.insert(1, note + "\n")
        return "".join(lines)

    @staticmethod
    def _strip_fences(text: str) -> str:
        """Remove triple-backtick fences the model may have added around the body."""
        stripped = text.strip()
        if stripped.startswith("```"):
            # Drop the first line (the opening fence, possibly with a
            # language tag).
            stripped = stripped.split("\n", 1)[-1]
        if stripped.endswith("```"):
            stripped = stripped.rsplit("```", 1)[0]
        return stripped.strip() + "\n"

    @staticmethod
    def _has_assertion(text: str, language: str) -> bool:
        """Return True if the generated text contains at least one assertion.

        Python: ``assert`` keyword or ``pytest.raises``.
        TS/JS: ``expect(...)`` or ``assert(...)`` from node:assert.
        Rust: ``assert!``, ``assert_eq!``, or ``assert_ne!`` macros.
        """
        if language == "python":
            return "assert " in text or "pytest.raises" in text
        if language == "rust":
            return "assert!" in text or "assert_eq!" in text or "assert_ne!" in text
        return "expect(" in text or "assert(" in text or "assert.equal" in text

    @staticmethod
    def _make_preview(text: str, *, max_lines: int = 20) -> str:
        lines = text.splitlines()
        if len(lines) <= max_lines:
            return "\n".join(lines)
        return "\n".join(lines[:max_lines]) + f"\n... ({len(lines) - max_lines} more lines)"
