"""Prompt templates for the test generator (Phase 1 Task 1.12b).

Each supported language has:
- A ``system`` prompt telling the model what role to play and what
  output format to use.
- A ``build_user_prompt`` function that wraps the source file text
  with language-specific instructions (framework choice, mandatory
  header, assertion requirements).

The templates are deliberately short. A longer template pulls the
model toward elaborate scaffolding that usually fails the per-language
compile check. A short template with one explicit rule per line
performs better on the compile gate in practice.
"""

from __future__ import annotations

SYSTEM_PROMPT = """You generate starter tests for source files.

Rules you must follow:
1. Output ONLY the test file contents. No markdown fencing, no prose, no explanations before or after.
2. Include the mandatory header on line 1 exactly as given in the user prompt.
3. Write at least one assertion that tests behavior, not implementation details.
4. Prefer tests that compile and pass over tests that fail. A passing test scaffold is more useful than a failing one because the user can expand from there.
5. Do not import modules that are not in the source file's imports or in the standard library for the target language. Do not assume the presence of helper libraries.
6. Do not wrap your output in triple backticks or any other markdown syntax.
7. Do not include comments that reference the generation process itself beyond the mandatory header.

You will be given the source file text and the target framework. Emit valid test code in that framework.
"""


RUST_SYSTEM_PROMPT = """You generate Rust test code for source files.

Rules you must follow:
1. Include the mandatory header comment on line 1 exactly as given in the user prompt.
2. Write at least one assertion using assert!, assert_eq!, or assert_ne! macros.
3. Do not wrap your output in triple backticks or any other markdown syntax.
4. Do not include comments that reference the generation process beyond the mandatory header.
5. Do not import external crates not already present in the source file's Cargo.toml.
6. For colocated style: output ONLY the #[cfg(test)] mod tests { ... } block. Do NOT include the surrounding source code.
7. For integration style: output a complete .rs file starting with the mandatory header comment.
8. All test functions must be annotated with #[test].
9. Prefer tests that compile and pass over tests that detect bugs, because a green scaffold is more useful as a starting point.
"""


def build_rust_user_prompt(
    *,
    source_path: str,
    source_text: str,
    style: str,
    crate_name: str,
    scope: str,
) -> str:
    """Assemble the user message for Rust test generation.

    ``style`` is either ``"colocated"`` (append a ``#[cfg(test)] mod tests``
    block to the source file) or ``"integration"`` (create a new file in
    ``tests/``).
    """
    scope_note = (
        "Cover every public function in this file."
        if scope == "module"
        else "Cover the first public function in this file."
    )
    header = "// generated by tailtest - review before committing"

    if style == "colocated":
        style_instructions = (
            "Output ONLY the #[cfg(test)] mod tests block -- "
            "do NOT include any of the surrounding source code shown below. "
            "Start with `use super::*;` inside the mod block to import the parent module."
        )
    else:
        style_instructions = (
            f"Output a complete integration test file. "
            f"Import from the crate with `use {crate_name}::*;` or specific paths."
        )

    return f"""Generate Rust tests for this source file.

## Source file path
{source_path}

## Crate name
{crate_name}

## Test style
{style}: {style_instructions}

## Scope
{scope_note}

## Mandatory header comment
The first line of your output MUST be exactly:
{header}

## Source file contents
```rust
{source_text}
```

## Your output
Emit ONLY the test code ({"#[cfg(test)] mod tests block" if style == "colocated" else "integration test file"}), starting with the mandatory header comment above. No markdown fences. No explanations.
"""


def build_user_prompt(
    *,
    source_path: str,
    source_text: str,
    language: str,
    framework: str,
    header_line: str,
    scope: str,
) -> str:
    """Assemble the user message passed to ``claude -p``.

    Parameters match ``TestGenerator.generate()``. ``scope`` is either
    ``"module"`` (cover the whole file) or ``"function"`` (cover a
    single exported entry point).
    """
    scope_note = (
        "Generate tests covering every public function or class in this file."
        if scope == "module"
        else "Generate a single focused test for the first public function in this file."
    )
    return f"""Generate a {framework} test for this {language} source file.

## Source file path
{source_path}

## Target framework
{framework}

## Scope
{scope_note}

## Mandatory header line
The first line of your output MUST be exactly:
{header_line}

## Source file contents
```
{source_text}
```

## Your output
Emit ONLY the test file contents, starting with the mandatory header line above. No markdown fences. No explanations. The file must parse as valid {language} and pass a {framework} collection check.
"""
