# Copyright 2026 AvanSaber Inc.
# SPDX-License-Identifier: Apache-2.0

"""``generate_tests`` MCP tool, real implementation (Phase 1 Task 1.12b)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, ClassVar

from tailtest.core.generator import (
    GeneratedTest,
    GenerationError,
    GeneratorSkipped,
    TestGenerator,
)
from tailtest.mcp.tools.base import BaseTool, ToolResponse, error_response, text_response

# Same 5KB truncation rule as run_tests (audit gap #5). Preview text
# caps at 20 lines, which is typically a few hundred bytes, well under
# the limit.
_MAX_TOOL_OUTPUT_BYTES = 5 * 1024


class GenerateTestsTool(BaseTool):
    name: ClassVar[str] = "generate_tests"
    description: ClassVar[str] = (
        "Generate starter tests for a source file. Writes tests in the project's "
        "native framework (pytest, vitest, jest) to the project's test directory "
        "with a 'generated by tailtest, review before committing' header. Never "
        "commits. Never overwrites an existing test file. Runs a per-language "
        "compile check before returning and deletes the file on failure."
    )
    input_schema: ClassVar[dict[str, Any]] = {
        "type": "object",
        "properties": {
            "file": {
                "type": "string",
                "description": "Path to the source file (absolute or relative to project root) to generate tests for.",
            },
            "style": {
                "type": "string",
                "enum": ["pytest", "vitest", "jest"],
                "description": "Optional framework override. Defaults to the detected native framework.",
            },
            "scope": {
                "type": "string",
                "enum": ["function", "module"],
                "description": "Whether to generate tests for a single function or the whole module. Defaults to module.",
                "default": "module",
            },
            "project_root": {
                "type": "string",
                "description": "Optional project root override. Defaults to the current working directory.",
            },
        },
        "required": ["file"],
    }

    async def invoke(self, arguments: dict[str, Any]) -> ToolResponse:
        file_arg = arguments.get("file")
        if not isinstance(file_arg, str) or not file_arg.strip():
            return error_response("generate_tests: 'file' argument is required")

        scope = arguments.get("scope", "module")
        if scope not in ("module", "function"):
            return error_response(
                f"generate_tests: invalid scope '{scope}', expected module or function"
            )

        style_override = arguments.get("style")
        project_root_arg = arguments.get("project_root")
        project_root = Path(project_root_arg) if project_root_arg else Path.cwd()
        project_root = project_root.resolve()

        source = Path(file_arg)
        if not source.is_absolute():
            source = (project_root / source).resolve()

        generator = TestGenerator(
            project_root,
            framework_override=style_override,
        )

        try:
            result = await generator.generate(source, scope=scope)
        except GeneratorSkipped as skip:
            payload = {
                "status": "skipped",
                "reason": str(skip),
                "source": str(source),
            }
            return text_response(self._truncate(json.dumps(payload, indent=2)))
        except GenerationError as exc:
            payload = {
                "status": "failed",
                "error": str(exc),
                "source": str(source),
            }
            return error_response(self._truncate(json.dumps(payload, indent=2)))

        payload = self._format_success(result)
        return text_response(self._truncate(json.dumps(payload, indent=2)))

    @staticmethod
    def _format_success(result: GeneratedTest) -> dict[str, Any]:
        return {
            "status": "ok",
            "source": str(result.source_path),
            "test_path": str(result.test_path),
            "language": result.language,
            "framework": result.framework,
            "preview": result.preview,
            "compile_check": {
                "tool": result.compile_check.tool,
                "ok": result.compile_check.ok,
                "message": result.compile_check.message,
            },
            "reminder": (
                "Review the generated test before committing. Tailtest never "
                "stages or commits files automatically."
            ),
        }

    @staticmethod
    def _truncate(text: str) -> str:
        """Cap the response at 5KB per audit gap #5."""
        if len(text.encode("utf-8")) <= _MAX_TOOL_OUTPUT_BYTES:
            return text
        # Truncate by decoding trick, keep the first N bytes and add a note.
        body = text.encode("utf-8")[: _MAX_TOOL_OUTPUT_BYTES - 80].decode("utf-8", errors="ignore")
        return body + "\n\n... (truncated at 5KB, see .tailtest/reports/latest.json)"
