"""``generate_tests`` MCP tool — Phase 1 stub; real implementation in Checkpoint F (Task 1.12b)."""

from __future__ import annotations

import json
from typing import Any, ClassVar

from tailtest.mcp.tools.base import BaseTool, ToolResponse, text_response


class GenerateTestsTool(BaseTool):
    name: ClassVar[str] = "generate_tests"
    description: ClassVar[str] = (
        "Generate starter tests for a source file. Writes tests in the project's "
        "native framework (pytest, vitest, jest, etc.) to the project's test "
        "directory with a `generated by tailtest` header comment. Never commits "
        "the generated file. Phase 1 status: STUB — returns 'not yet implemented'. "
        "Real implementation ships in Phase 1 Checkpoint F (Task 1.12b)."
    )
    input_schema: ClassVar[dict[str, Any]] = {
        "type": "object",
        "properties": {
            "file": {
                "type": "string",
                "description": "Path to the source file (relative to project root) to generate tests for.",
            },
            "style": {
                "type": "string",
                "enum": ["pytest", "vitest", "jest"],
                "description": "Optional override; defaults to the detected native framework.",
            },
            "scope": {
                "type": "string",
                "enum": ["function", "module"],
                "description": "Whether to generate tests for a single function or the whole module.",
                "default": "module",
            },
        },
        "required": ["file"],
    }

    async def invoke(self, arguments: dict[str, Any]) -> ToolResponse:
        file_arg = arguments.get("file", "")
        payload = {
            "status": "not_yet_implemented",
            "file": file_arg,
            "message": (
                "generate_tests is a Phase 1 stub. The real implementation "
                "lands in Phase 1 Checkpoint F as Task 1.12b (TestGenerator). "
                "Until then, write starter tests by hand or wait for the "
                "generator to ship."
            ),
            "scheduled_checkpoint": "F",
            "tracking_task": "1.12b",
        }
        return text_response(json.dumps(payload, indent=2))
