# Copyright 2026 AvanSaber Inc.
# SPDX-License-Identifier: Apache-2.0

"""ConfigLoader — read/write ``.tailtest/config.yaml``.

Per the audit (gap #4), config is loaded fresh on every PostToolUse
hook invocation rather than cached at import time. ConfigLoader is a
thin wrapper around yaml + Pydantic that enforces that discipline.
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

from tailtest.core.config.schema import CONFIG_SCHEMA_VERSION, Config

logger = logging.getLogger(__name__)


_DEFAULT_HEADER = f"""# tailtest configuration
#
# Generated by tailtest {CONFIG_SCHEMA_VERSION!s} at first install. Edit directly
# or via `tailtest config <key> <value>` (Phase 2+).
#
# depth: off | quick | standard | thorough | paranoid
#   See ADR 0002 for the depth-mode rationale and which features
#   land at which depth.
#
# runners.auto_detect: true (default) lets the scanner pick runners
#   based on what it finds. Custom runners are a Phase 2 feature.
#
# security.*: off by default in Phase 1. The security layer lands in
#   Phase 2 and these flags become meaningful then.
#
# notifications.auto_offer_generation: when true (default), tailtest
#   suggests generating starter tests for newly added uncovered
#   functions. Disable to reduce noise.
#
"""


class ConfigLoader:
    """Reads and writes ``.tailtest/config.yaml``.

    Parameters
    ----------
    tailtest_dir:
        The project's ``.tailtest/`` directory. The config file lives at
        ``<tailtest_dir>/config.yaml``. Created on first write.
    """

    def __init__(self, tailtest_dir: Path) -> None:
        self._tailtest_dir = tailtest_dir

    @property
    def config_path(self) -> Path:
        return self._tailtest_dir / "config.yaml"

    def exists(self) -> bool:
        return self.config_path.exists()

    def load(self) -> Config:
        """Load the config from disk, or return defaults if missing.

        On parse errors, logs a warning and returns defaults rather
        than raising — the hot loop must never be taken down by a
        malformed config.
        """
        if not self.config_path.exists():
            return Config()
        try:
            text = self.config_path.read_text(encoding="utf-8")
            data = yaml.safe_load(text) or {}
            if not isinstance(data, dict):
                logger.warning("config.yaml is not a mapping; using defaults")
                return Config()
            return Config.model_validate(data)
        except yaml.YAMLError as exc:
            logger.warning("config.yaml is not valid YAML: %s; using defaults", exc)
            return Config()
        except Exception as exc:  # noqa: BLE001 — defensive
            logger.warning("config.yaml failed to validate: %s; using defaults", exc)
            return Config()

    def save(self, config: Config, *, include_header: bool = True) -> Path:
        """Atomically write the config to disk.

        Writes to a temp file in the same directory, then renames over
        the target path so a crash during write can't leave a partial
        config file.
        """
        self._tailtest_dir.mkdir(parents=True, exist_ok=True)
        data = config.model_dump(mode="json", exclude_defaults=False)
        yaml_text = yaml.safe_dump(data, sort_keys=False, default_flow_style=False)

        content = (_DEFAULT_HEADER + yaml_text) if include_header else yaml_text

        tmp = self.config_path.with_suffix(".yaml.tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(self.config_path)
        return self.config_path

    def ensure_default(self) -> Config:
        """Load existing config, or create + save defaults if missing.

        Returns the loaded or freshly-created Config.
        """
        if self.config_path.exists():
            return self.load()
        config = Config()
        self.save(config)
        return config
